<?php
/*
 * This file is part of the Maker plugin
 *
 * Copyright (C) 2016 LOCKON CO.,LTD. All Rights Reserved.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\Maker\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Plugin\Maker\Entity\Maker;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * Maker.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MakerRepository extends ServiceEntityRepository
{

    /**
     * MakerRepository constructor.
     *
     * @param RegistryInterface $registry
     * @param string $entityClass
     */
    public function __construct(RegistryInterface $registry, string $entityClass = Maker::class)
    {
        parent::__construct($registry, $entityClass);
    }

    /**
     * Save method.
     *
     * @param Maker $Maker
     *
     * @return bool
     */
    public function save($Maker)
    {
        $em = $this->getEntityManager();
        try {
            if (!$Maker->getId()) {
                $rank = $this->createQueryBuilder('m')
                    ->select('MAX(m.rank)')
                    ->getQuery()
                    ->getSingleScalarResult();
                if (!$rank) {
                    $rank = 0;
                }
                $Maker->setRank($rank + 1);

                $em->createQueryBuilder()
                    ->update('Plugin\Maker\Entity\Maker', 'm')
                    ->set('m.rank', 'm.rank + 1')
                    ->where('m.rank > :rank')
                    ->setParameter('rank', $rank)
                    ->getQuery()
                    ->execute();
            }

            $em->persist($Maker);
            $em->flush($Maker);
        } catch (\Exception $e) {
            return false;
        }

        return true;
    }

    /**
     * Delete maker.
     *
     * @param Maker $Maker
     *
     * @return bool
     */
    public function delete($Maker)
    {
        $em = $this->getEntityManager();
        try {
            $em->remove($Maker);
            $em->flush($Maker);
        } catch (\Exception $e) {
            return false;
        }

        return true;
    }

    /**
     * Move rank.
     *
     * @param array $arrRank
     *
     * @return array
     *
     * @throws \Exception
     */
    public function moveMakerRank(array $arrRank)
    {
        $arrMoveRank = [];
        try {
            foreach ($arrRank as $makerId => $rank) {
                /* @var $Maker Maker */
                $Maker = $this->find($makerId);
                if ($Maker->getRank() == $rank) {
                    continue;
                }
                $arrMoveRank[$makerId] = $rank;
                $Maker->setRank($rank);
                $this->getEntityManager()->persist($Maker);
                $this->getEntityManager()->flush($Maker);
            }
        } catch (\Exception $e) {
            throw $e;
        }

        return $arrMoveRank;
    }
}
