<?php
/*
* This file is part of EC-CUBE
*
* Copyright(c) 2000-2015 LOCKON CO.,LTD. All Rights Reserved.
* http://www.lockon.co.jp/
*
* For the full copyright and license information, please view the LICENSE
* file that was distributed with this source code.
*/

namespace Plugin\Maker\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * Maker
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MakerRepository extends EntityRepository
{
    /**
     * find all
     *
     * @return type
     */
    public function findAll()
    {

        $query = $this
            ->getEntityManager()
            ->createQuery('SELECT m FROM Plugin\Maker\Entity\Maker m ORDER BY m.rank DESC');
        $result = $query
            ->getResult(Query::HYDRATE_ARRAY);

        return $result;
    }

    /**
     * @param  \Plugin\Maker\Entity\Maker $Maker
     * @return void
     */
    public function up(\Plugin\Maker\Entity\Maker $Maker)
    {
        $em = $this->getEntityManager();
        $em->getConnection()->beginTransaction();
        try {
            $rank = $Maker->getRank();

            $MakerUp = $this->createQueryBuilder('m')
                ->where('m.rank > :rank')
                ->setParameter('rank', $rank)
                ->orderBy('m.rank', 'ASC')
                ->setMaxResults(1)
                ->getQuery()
                ->getSingleResult();

            $Maker->setRank($MakerUp->getRank());
            $MakerUp->setRank($rank);

            $em->persist($Maker);
            $em->persist($MakerUp);

            $em->flush();
            $em->getConnection()->commit();
        } catch (\Exception $e) {
            $em->getConnection()->rollback();

            return false;
        }

        return true;
	}

    /**
     * @param  \Plugin\Maker\Entity\Maker $Maker
     * @return bool
     */
    public function down(\Plugin\Maker\Entity\Maker $Maker)
    {
        $em = $this->getEntityManager();
        $em->getConnection()->beginTransaction();
        try {
            $rank = $Maker->getRank();

            $MakerDown = $this->createQueryBuilder('m')
                ->where('m.rank < :rank ')
                ->setParameter('rank', $rank)
                ->orderBy('m.rank', 'DESC')
                ->setMaxResults(1)
                ->getQuery()
                ->getSingleResult();

            $Maker->setRank($MakerDown->getRank());
            $MakerDown->setRank($rank);

            $em->persist($Maker);
            $em->persist($MakerDown);
            $em->flush();

            $em->getConnection()->commit();
        } catch (\Exception $e) {
            $em->getConnection()->rollback();

            return false;
        }

        return true;
    }

    /**
     * @param  \Plugin\Maker\Entity\Maker $Maker
     * @return bool
     */
    public function save(\Plugin\Maker\Entity\Maker $Maker)
    {
        $em = $this->getEntityManager();
        $em->getConnection()->beginTransaction();
        try {
            if (!$Maker->getId()) {
                $rank = $this->createQueryBuilder('m')
                    ->select('MAX(m.rank)')
                    ->getQuery()
                    ->getSingleScalarResult();
                if (!$rank) {
                    $rank = 0;
                }
                $Maker->setRank($rank + 1);
                $Maker->setDelFlg(0);

                $em->createQueryBuilder()
                    ->update('Plugin\Maker\Entity\Maker', 'm')
                    ->set('m.rank', 'm.rank + 1')
                    ->where('m.rank > :rank')
                    ->setParameter('rank', $rank)
                    ->getQuery()
                    ->execute();
            }

            $em->persist($Maker);
            $em->flush();

            $em->getConnection()->commit();
        } catch (\Exception $e) {
            $em->getConnection()->rollback();

            return false;
        }
        return true;
    }

    /**
     * @param  \Plugin\Maker\Entity\Maker $Maker
     * @return bool
     */
    public function delete(\Plugin\Maker\Entity\Maker $Maker)
    {
        $em = $this->getEntityManager();
        $em->getConnection()->beginTransaction();
        try {
            $Maker->setDelFlg(1);
            $em->persist($Maker);
            $em->flush();

            $em->getConnection()->commit();
        } catch (\Exception $e) {
            $em->getConnection()->rollback();

            return false;
        }

        return true;
    }

}
