<?php
/*
 * This file is part of the Maker plugin
 *
 * Copyright (C) 2016 LOCKON CO.,LTD. All Rights Reserved.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\Maker\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Plugin\Maker\Entity\ProductMaker;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * Maker.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductMakerRepository extends ServiceEntityRepository
{
    /**
     * MakerRepository constructor.
     *
     * @param RegistryInterface $registry
     * @param string $entityClass
     */
    public function __construct(RegistryInterface $registry, string $entityClass = ProductMaker::class)
    {
        parent::__construct($registry, $entityClass);
    }
}
